export const FETCH_ARCHIVES = 'FETCH_ARCHIVES';
export const ACTION_ARCHIVE = 'ACTION_ARCHIVE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const POST_ACTION_SUCCESS = "POST_ACTION_SUCCESS";
export const POST_ACTION_FAIL = "POST_ACTION_FILE";
export const ARCHIVE_ACTION_SUCCESS = "ARCHIVE_ACTION_SUCCESS";
export const ARCHIVE_ACTION_FAIL = "ARCHIVE_ACTION_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCES";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";